language: node_js
node_js:
  - "v10.15.3"
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  directories:
    - node_modules
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY
  local_dir: build/dist
  on:
    branch: esa